spring:
  profiles:
    active: develop

server:
  port: 8100

rest:
  userService:
    url: ${USER_SERVICE_URL:http://localhost:8081}

grpc:
  client:
    ticket:
      address: ${TICKETS_GRPC_URL:static://localhost:9000}
      negotiationType: PLAINTEXT
