version: "3.8"
services:
  eventlogs:
    image: mongo:5.0.26-focal
    container_name: "eventlogs"
    ports:
      - 57017:27017
    volumes:
      - mongodb_data_bff:/data/db
  ticketsbffweb:
    image: bff:4.0
    container_name: "ticketsbffweb"
    ports:
      - 8100:8100
    links:
      - eventlogs

volumes:
  mongodb_data_bff:


