version: "3.8"
services:
  eventticketsmongo:
    image: mongo:5.0.26-focal
    container_name: "eventticketsmongo"
    ports:
      - 47017:27017
    volumes:
      - mongodb_data:/data/db

  eventtickts:
    image: majar4601/eventtickets-jvm:latest
    environment:
      - QUARKUS_MONGODB_CONNECTION_STRING=mongodb://eventticketsmongo:27017/
    container_name: "eventtickets"
    ports:
      - 9000:9000
    depends_on:
      - eventticketsmongo

volumes:
  mongodb_data: