version: "3.8"
services:
  mongodb:
    image: mongo:5.0.26-focal
    container_name: "mongodb"
    ports:
      - 27070:27017

  eventusers:
    build: .
    container_name: "eventusers"
    ports:
      - 8081:8081



