version: "3.8"
services:
  mongodb:
    image: mongo:5.0.25-focal
    container_name: "mongodb"
    ports:
      - 27070:27017

  ticketuser:
    build: .
    restart: always
    container_name: "ticketuser"
    ports:
      - 8081:8081
    depends_on:
      - mongodb