version: "3.8"
services:
  mongodb:
    image: mongo:5.0.25-focal
    container_name: "mongodb"
    ports:
      - 27070:27017
    volumes:
      - ~/mongo/data:/data/db

  users:
    build: .
    restart: always
    container_name: "eventusers"
    ports:
      - 8080:8080
    depends_on:
      - mongodb