spring:
  profiles:
    active: develop

  data:
    mongodb:
      database: logs
      host: eventlogmongo
      port: 27017

server:
  port: 8100

rest:
  userService:
    url: ${USER_SERVICE_URL:http://eventusers:8081}

grpc:
  client:
    ticket:
      address: ${TICKETS_GRPC_URL:static://eventtickets:9000}
      negotiationType: PLAINTEXT
