version: "3.8"
services:
  eventpaymentsmongo:
    image: mongo:5.0.26-focal
    container_name: "eventpaymentsmongo"
    ports:
      - 37017:27017
    volumes:
      - mongodb_data:/data/db

  eventpayments:
    image: quarkus/eventpayments-jvm:latest
    container_name: "eventpayments"
    environment:
      - QUARKUS_MONGODB_CONNECTION_STRING=mongodb://eventpaymentsmongo:27017/
    ports:
      - 8082:8082
    depends_on:
      - eventpaymentsmongo

volumes:
  mongodb_data:
